### ISSUE TITLE
Include containership.io/name label to all resources that have an accompanying cloud name

### ISSUE THREAD

**Issue by nicktate** [containership/cluster-manager#78]
#### Why should this feature be added?
Currently we store many resources as `uid` inside kubernetes to prevent clashes. We should create a uniform label across all of our resources that can be referenced

#### How would you like the feature to work?
Create `containership.io/name: {name}` label on all resources where the synced cloud resource has a `name` key

**Comment by mattkelly** [comment]
The only resource for which this is particularly useful is a Kubernetes ClusterRole synced from a CR. This is the only native Kubernetes resource we sync which has a `name` field in the CR.

In order to do this, we would need to come up with a scheme to convert our cloud names (which are not really restricted) to labels (which are very restricted). This could be e.g. converting all disallowed characters to `-`. 

I personally don't feel that this is worth it after thinking about it more. I think it will bring more confusion than anything. We can always identify the owning CR by checking the owner reference.

**Comment by mattkelly** [comment]
Discussed with @nicktate via Slack. We've agreed to just close this.
